name: Solicitar evolução
description: Proponha uma fonte, regra, canal ou melhoria
title: '[FEATURE] '
labels: ['enhancement']
body:
  - type: textarea
    id: scenario
    attributes:
      label: Cenário de negócio
      description: Explique a fonte, os critérios, destinatários e resultado esperado.
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Critérios de aceite
    validations:
      required: true
